version: '3.3'
services:
  db-1:
    image: mysql
    container_name: "db-1"
    ports:
      - "3310:3306"
    volumes:
      - db_data_1:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=users        
  db-2:
    image: mysql
    container_name: "db-2"
    ports:
      - "3311:3306"
    volumes:
      - db_data_2:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=users
volumes:
  db_data_1: {}
  db_data_2: {}
